<a href="https://colab.research.google.com/github/yougshree/Data-Science-Interview-Preparation/blob/main/Pandas%20Interview%20Preparation/Practice_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# 1.Create dataframe
df= pd.DataFrame([11, 20, 30],columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        20
2        30

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
data= {
    'Name': ['Mina', 'Dina', 'Rina', 'Simu'],
    'Age': [22, 32, 40, 38],
    'Salary':[20000, 32000, 380000, 34000]
}

In [ ]:
df= pd.DataFrame(data)
print(df)

   Name  Age  Salary
0  Mina   22   20000
1  Dina   32   32000
2  Rina   40  380000
3  Simu   38   34000

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
#Basic

In [ ]:
df.head() #top five

   Name  Age  Salary
0  Mina   22   20000
1  Dina   32   32000
2  Rina   40  380000
3  Simu   38   34000

In [ ]:
df.head(10) # top ten

   Name  Age  Salary
0  Mina   22   20000
1  Dina   32   32000
2  Rina   40  380000
3  Simu   38   34000

In [ ]:
df.tail() # last five

   Name  Age  Salary
0  Mina   22   20000
1  Dina   32   32000
2  Rina   40  380000
3  Simu   38   34000

In [ ]:
df.shape # find total col and rows

(4, 3)

In [ ]:
df.columns # columns name

Index(['Name', 'Age', 'Salary'], dtype='object')

In [ ]:
df.rename(columns= {'Salary': 'Monthly_Salary'}, inplace= True) # permanetly change by using true

In [ ]:
df

   Name  Age  Salary
0  Mina   22   20000
1  Dina   32   32000
2  Rina   40  380000
3  Simu   38   34000

In [ ]:
df.info() #information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

             Age         Salary
count   4.000000       4.000000
mean   33.000000  116500.000000
std     8.082904  175775.424903
min    22.000000   20000.000000
25%    29.500000   29000.000000
50%    35.000000   33000.000000
75%    38.500000  120500.000000
max    40.000000  380000.000000

In [ ]:
#3 save and load data from csv
df.to_csv('Test_data.csv', index='False') #index value will be deleted

In [ ]:
df1= pd.read_csv('Test_data.csv')
print(df1)
import pandas as pd

   Unnamed: 0  Name  Age  Salary
0           0  Mina   22   20000
1           1  Dina   32   32000
2           2  Rina   40  380000
3           3  Simu   38   34000

In [ ]:
#4 rows & columns selection

In [ ]:
#slect single column
df1[['Name']]

   Name
0  Mina
1  Dina
2  Rina
3  Simu

In [ ]:
#single multiple
df1[['Name', 'Salary']]

   Name  Salary
0  Mina   20000
1  Dina   32000
2  Rina  380000
3  Simu   34000

In [ ]:
#select row
df1

   Unnamed: 0  Name  Age  Salary
0           0  Mina   22   20000
1           1  Dina   32   32000
2           2  Rina   40  380000
3           3  Simu   38   34000

In [ ]:
# rows
df1.loc[(df1.Name=='Dina')& (df1.Monthly_Salary>=30000)]
df1 # error answer

   Name  Age  Monthly_Salary
0  Mina   22           20000
1  Dina   32           32000
2  Rina   40          380000
3  Simu   38           34000

In [ ]:
#index value
df1.iloc[0]

Name               Mina
Age                  22
Monthly_Salary    20000
Name: 0, dtype: object

In [ ]:
df1.iloc[0:2] # give first two array start count from 0. 0->1, 1->2

   Name  Age  Monthly_Salary
0  Mina   22           20000
1  Dina   32           32000

In [ ]:
df.loc[0:2] #array start from 0

   Name  Age  Monthly_Salary
0  Mina   22           20000
1  Dina   32           32000
2  Rina   40          380000

In [ ]:
#filter dataframe
df1= [df1['Age']>= 18]
df1

[0    True
 1    True
 2    True
 3    True
 Name: Age, dtype: bool]

In [ ]:
df1= (df1(['Age']>= 18) & (df1['Monthly_Salary']>=30000))
df1

TypeError: '>=' not supported between instances of 'list' and 'int'

In [ ]:
#5 dataframe selection